//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databasenoteused
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoDataModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhotoDataModel()
        {
            this.CommentsDataModels = new HashSet<CommentsDataModel>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Datecreated { get; set; }
        public Nullable<System.DateTime> Dateupdated { get; set; }
        public bool publik { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserID { get; set; }
        public int AlbumID { get; set; }
    
        public virtual AlbumDataModel AlbumDataModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentsDataModel> CommentsDataModels { get; set; }
        public virtual UserDataModel UserDataModel { get; set; }
    }
}
